openapi: 3.0.0
x-stoplight:
  id: 8tlfrgw6uetjc
info:
  title: FROS
  version: '1.0'
  description: FROSのAPI仕様書
  contact:
    name: nothing
servers:
  - url: 'http://localhost:3000'
paths:
  '/users/{userid}':
    get:
      summary: ユーザー情報管理API
      tags:
        - users
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  info:
                    $ref: '#/components/schemas/user'
                  skills:
                    type: array
                    items:
                      $ref: '#/components/schemas/skill'
                  certifications:
                    type: array
                    items:
                      $ref: '#/components/schemas/certification'
                  authorities:
                    type: array
                    items:
                      $ref: '#/components/schemas/authority'
        '204':
          description: No Content
        '400':
          description: Bad Request
      operationId: 'get-users-[userid]'
      description: ユーザー情報取得
      parameters: []
      x-internal: false
    put:
      summary: ''
      operationId: 'put-users-[userid]'
      description: ユーザー情報編集
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                skills:
                  type: array
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/skill'
                certifications:
                  type: array
                  items:
                    $ref: '#/components/schemas/certification'
                authorities:
                  type: array
                  items:
                    $ref: '#/components/schemas/authority'
      tags:
        - users
      responses:
        '200':
          description: OK
    parameters:
      - schema:
          type: string
        name: userid
        in: path
        required: true
  /skills:
    get:
      summary: Your GET endpoint
      tags:
        - skills
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  skills:
                    type: array
                    description: 登録されているskillが配列で帰ってくる
                    items:
                      type: string
        '400':
          description: Bad Request
      operationId: get-skills
      description: スキル一覧取得
  /certifications:
    get:
      summary: Your GET endpoint
      tags:
        - certifications
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  skill:
                    type: string
        '400':
          description: Bad Request
      operationId: get-certifications
      description: 資格一覧取得
  /authorities:
    get:
      summary: Your GET endpoint
      tags:
        - authorities
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  authorities:
                    type: array
                    items:
                      type: string
        '400':
          description: Bad Request
      operationId: get-authorities
      description: 権限情報一覧取得
  /users:
    post:
      summary: ''
      operationId: post-users
      responses:
        '201':
          description: Created
      tags:
        - users
      description: ユーザー情報登録
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: firebaseから受け取る一意のid
                name:
                  type: string
                  description: ユーザー名
                email:
                  type: string
                  description: email
                image:
                  type: string
                  description: 画像のurl
        description: ''
  /search/skills:
    get:
      summary: Your GET endpoint
      tags:
        - search
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  list:
                    type: array
                    items:
                      type: object
                      properties:
                        user:
                          type: object
                          properties:
                            id:
                              type: string
                              description: ユーザーid
                            name:
                              type: string
                              description: ユーザー名
                        skills:
                          type: array
                          description: userが持っているskill一覧の配列
                          items:
                            type: string
        '400':
          description: Bad Request
      operationId: get-search-skills
      description: スキル検索
      parameters:
        - schema:
            type: string
          in: query
          name: text
          description: 検索内容
  /search/certifications:
    get:
      summary: Your GET endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  list:
                    type: array
                    items:
                      type: object
                      properties:
                        user:
                          type: object
                          properties:
                            id:
                              type: string
                              description: |
                                ユーザーid
                            name:
                              type: string
                              description: ユーザー名
                        certification:
                          type: object
                          properties:
                            name:
                              type: string
                              description: 資格名
                            expiration:
                              type: string
                              description: 資格の有効期限
        '400':
          description: Bad Request
      operationId: get-search-certifications
      description: 資格検索
      parameters:
        - schema:
            type: string
          in: query
          name: text
          description: 検索内容
      tags:
        - search
  /search/authorities:
    get:
      summary: Your GET endpoint
      tags:
        - search
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  list:
                    type: array
                    items:
                      type: object
                      properties:
                        user:
                          type: object
                          properties:
                            id:
                              type: string
                              description: ユーザー名
                            name:
                              type: string
                              description: ユーザー名
                        authority:
                          type: string
                          description: 権限情報名
        '400':
          description: Bad Request
      operationId: get-search-authorities
      description: 権限情報検索
      parameters:
        - schema:
            type: string
          in: query
          name: text
          description: 検索内容
  /search/users:
    get:
      summary: Your GET endpoint
      tags:
        - search
      operationId: get-search-users
      description: ユーザー名検索のAPI
      parameters:
        - schema:
            type: string
          in: query
          name: text
          description: 検索内容（ユーザー名）
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  list:
                    type: array
                    items:
                      type: object
                      properties:
                        user:
                          type: object
                          description: 他のAPIと合わせるためにuserObjectの中に入れてます
                          properties:
                            id:
                              type: string
                              description: ユーザーid
                            name:
                              type: string
                              description: ユーザー名
        '400':
          description: Bad Request
components:
  schemas:
    skill:
      title: skill
      x-stoplight:
        id: i6jbotg7kmi6r
      type: object
      description: skill
      properties:
        id:
          type: string
        name:
          type: string
          description: スキル名
        level:
          type: integer
          minimum: 0
          maximum: 5
    certification:
      title: certification
      x-stoplight:
        id: h52jsyru8x4k2
      type: object
      properties:
        id:
          type: string
        name:
          type: string
          description: 資格名
          example: AZ-104
    user:
      title: user
      x-stoplight:
        id: z6f6l8b36wynu
      type: object
      properties:
        id:
          type: string
        service_line:
          type: string
        joining_day:
          type: string
        email:
          type: string
        isAdmin:
          type: string
    authority:
      title: authority
      x-stoplight:
        id: 8hh9xxqua683z
      type: object
      properties:
        id:
          type: string
        name:
          type: string
  responses: {}
security: []
tags:
  - name: authorities
  - name: certifications
  - name: search
  - name: skills
  - name: users
