openapi: 3.0.0
x-stoplight:
  id: 8tlfrgw6uetjc
info:
  title: FROS
  version: '1.0'
  description: FROSのAPI仕様書
  contact:
    name: nothing
servers:
  - url: 'http://localhost:8080'
    description: 開発環境
paths:
  '/users/{userid}':
    get:
      summary: ユーザー情報取得
      tags:
        - users
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userResponse'
              examples:
                Example 1:
                  value:
                    id: string
                    name: string
                    image: string
                    email: string
                    service_line: string
                    fros_privilege: string
                    skills:
                      - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                        name: string
                        level: 0
                    privileges:
                      - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                        name: string
                    certifications:
                      - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                        name: string
                        expiration: '2019-08-24'
        '400':
          description: Bad Request
        '404':
          description: |-
            Not Found
            userが見つからないとき
        '500':
          description: Internal Server Error
      operationId: 'get-users-[userid]'
      description: ユーザー情報取得
      parameters: []
      x-internal: false
    parameters:
      - schema:
          type: string
        name: userid
        in: path
        required: true
  /skills:
    get:
      summary: スキル一覧取得
      tags:
        - skills
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/skillResponse'
              examples:
                Example 1:
                  value:
                    - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                      name: string
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      operationId: get-skills
      description: スキル一覧取得
  /certifications:
    get:
      summary: 資格一覧取得
      tags:
        - certifications
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/cetificationResponse'
              examples:
                Example 1:
                  value:
                    - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                      name: string
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      operationId: get-certifications
      description: 資格一覧取得
      x-extension-1: null
  /privileges:
    get:
      summary: 権限情報一覧取得
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/privilegeResponse'
              examples:
                Example 1:
                  value:
                    - id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                      name: string
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      operationId: get-authorities
      description: 権限情報一覧取得
      tags:
        - privileges
    parameters: []
  /users:
    post:
      summary: ユーザー情報登録
      operationId: post-users
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      tags:
        - users
      description: ユーザー情報登録
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/userReqest'
            examples:
              Example 1:
                value:
                  id: 497f6eca-6276-4993-bfeb-53cbbbba6f08
                  name: string
                  email: user@example.com
                  image: string
                  fros_privilege: 'None '
                  service_line_id: 0
        description: ''
    put:
      summary: ユーザー情報更新
      operationId: put-users
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userResponse'
        '400':
          description: Bad Request
        '404':
          description: |-
            Not Found
            userが見つからないとき？
        '500':
          description: Internal Server Error
      description: ユーザー更新
      tags:
        - users
  /users/search/skills:
    get:
      summary: スキルによるユーザー検索
      responses:
        '200':
          description: OK
          headers: {}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userResponse'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      operationId: get-search-skills
      description: スキル検索
      parameters:
        - schema:
            type: string
          in: query
          name: id
          description: スキルのuuid
      tags:
        - users
    parameters: []
  /users/search/certifications:
    get:
      summary: 資格によるユーザー検索
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userReqest'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      operationId: get-search-certifications
      description: 資格検索
      parameters:
        - schema:
            type: string
          in: query
          name: id
          description: 資格のuuid
      tags:
        - users
    parameters: []
  /users/search/privileges:
    get:
      summary: 権限情報によるユーザ検索
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userReqest'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      operationId: get-search-authorities
      description: 権限情報検索
      parameters:
        - schema:
            type: string
          in: query
          name: id
          description: 権限情報のuuid
      tags:
        - users
    parameters: []
  /users/search/name:
    get:
      summary: ユーザー名によるユーザ検索
      operationId: get-search-users
      description: ユーザー名検索のAPI
      parameters:
        - schema:
            type: string
          in: query
          name: name
          description: 検索内容（ユーザー名）
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userReqest'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
      tags:
        - users
    parameters: []
  /users/skills:
    put:
      summary: ユーザースキル更新
      operationId: put-users-skills
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userResponse'
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties: {}
            application/xml:
              schema:
                type: object
                properties: {}
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      description: ユーザーのスキル更新
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                  description: ユーザーID
                skills:
                  type: array
                  items:
                    $ref: '#/components/schemas/skillRequest'
        description: ''
      tags:
        - users
  /users/privileges:
    put:
      summary: ユーザー権限情報更新
      operationId: put-users-privileges
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userResponse'
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      description: ユーザーの権限情報更新
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                privileges:
                  format: uuid
                  type: array
                  items:
                    $ref: '#/components/schemas/privilegeReqest'
          application/xml:
            schema:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                '':
                  type: string
        description: ''
      tags:
        - users
    parameters: []
  /users/certifications:
    put:
      summary: ユーザー資格更新
      operationId: put-users-certifications
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userResponse'
            application/xml:
              schema:
                type: object
                properties: {}
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
      description: ユーザーの資格更新
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                  format: uuid
                certifications:
                  type: array
                  items:
                    $ref: '#/components/schemas/certificationReqest'
        description: ''
      tags:
        - users
  /servicelines:
    get:
      summary: サービスライン一覧取得
      tags:
        - serviceLines
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/servicelineRequest'
      operationId: get-servicelines
      description: サービスライン一覧取得
    parameters: []
components:
  schemas:
    skillRequest:
      title: skillRequest
      x-stoplight:
        id: 792ca8ef23bb7
      type: object
      description: skill
      properties:
        id:
          type: string
          description: uuid
          format: uuid
        level:
          type: number
    skillResponse:
      title: skillResponse
      x-stoplight:
        id: psb5stvi2zg2n
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    privilegeReqest:
      title: privilegeReqest
      x-stoplight:
        id: 299425a98218f
      type: object
      properties:
        id:
          type: string
          format: uuid
    privilegeResponse:
      title: privilegeResponse
      x-stoplight:
        id: 4nt339fvsh0q7
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    certificationReqest:
      title: certificationRequest
      x-stoplight:
        id: 3a9e55306528a
      type: object
      properties:
        id:
          type: string
          description: uuid
          format: uuid
    cetificationResponse:
      title: cetificationResponse
      x-stoplight:
        id: s9ejm5twwab0t
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    userReqest:
      title: userReqest
      x-stoplight:
        id: 5b38xorcopbd0
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        email:
          type: string
          format: email
        image:
          type: string
        fros_privilege:
          type: string
          enum:
            - 'None '
            - Edit
            - View
        service_line_id:
          type: number
    userResponse:
      title: userResponse
      x-stoplight:
        id: 23f6c782ee858
      type: object
      properties:
        id:
          type: string
          description: uuid
        name:
          type: string
        image:
          type: string
        email:
          type: string
        service_line:
          type: string
        fros_privilege:
          type: string
        skills:
          type: array
          items:
            $ref: '#/components/schemas/userSkillResponse'
        privileges:
          type: array
          items:
            $ref: '#/components/schemas/userPrivilegeResponse'
        certifications:
          type: array
          items:
            $ref: '#/components/schemas/userCertificationResponse'
    servicelineRequest:
      title: servicelineRequest
      x-stoplight:
        id: z27mtrmhd2pq1
      type: object
      properties:
        id:
          type: string
        name:
          type: string
    userSkillResponse:
      title: userSkillResponse
      x-stoplight:
        id: fbkhfo6uwekxf
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        level:
          type: number
    userPrivilegeResponse:
      title: userPrivilegeResponse
      x-stoplight:
        id: 4wxswvctzjxci
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
    userCertificationResponse:
      title: userCertificationResponse
      x-stoplight:
        id: cdectkp7xua3c
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        expiration:
          type: string
          format: date
  responses: {}
security: []
tags:
  - name: certifications
  - name: privileges
  - name: serviceLines
  - name: skills
  - name: users
